version: '3'
services: 
  tully:
    image: tullyapps/mongo-logs
    build:
      context: ./
      dockerfile: mongo.DockerFile
    environment:
        # provide your credentials here
        - MONGO_INITDB_DATABASE=logs
        - MONGO_INITDB_ROOT_USERNAME=tully
        - MONGO_INITDB_ROOT_PASSWORD=tullylogs
    ports:
      - "27020:27017"
    volumes:
        - /home/kathan/mongo-data:/data/db
        # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
        # - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    # no --auth is needed here as presence of username and password add this option automatically
    # command: mongod
